### PR TITLE
Fix error in NetworkStatus struct change in multus-cni

### PR DESCRIPTION
**Pull request by krsacme**
Dependency is updated. NetworkStatus was changed in commit
https://github.com/intel/multus-cni/commit/3a9dd7ed76087062e067866a53ec8e0c9e67cef3

### CODE REVIEW

**Comment by zenghui-shi** [comment]
@krsacme hi, thanks for the PR!

Two files are still using `Default` in `NetworkData`:
```
./pkg/userspace/userspace.go
./pkg/types/types.go
```

**Comment by zenghui-shi** [comment]
/lgtm

@Billy99 PTAL

**Review by Billy99 — APPROVED** [review]
/lgtm

My only comment is that there is a sample annotations file [annotations_all](https://github.com/openshift/app-netutil/blob/master/samples/annotations/annotations_all) which allows app-netutil to be run locally (see [go_app/README](https://github.com/openshift/app-netutil/blob/master/samples/go_app/README.md) and [c_app/README.md](https://github.com/openshift/app-netutil/blob/master/samples/c_app/README.md)). It should be updated as well.

**Comment by krsacme** [comment]
> /lgtm
> 
> My only comment is that there is a sample annotations file [annotations_all](https://github.com/openshift/app-netutil/blob/master/samples/annotations/annotations_all) which allows app-netutil to be run locally (see [go_app/README](https://github.com/openshift/app-netutil/blob/master/samples/go_app/README.md) and [c_app/README.md](https://github.com/openshift/app-netutil/blob/master/samples/c_app/README.md)). It should be updated as well.

Thanks for the pointers. I have updated the sample files. Here is the sample output with go app:

```
| 0       |: IfName=  Name=cbr0  Type=kernel
|         |:   &{IPs:[10.244.1.32] Mac: DNS:{Nameservers:[] Domain: Search:[] Options:[]} Gateway:[10.244.1.1]}
| 1       |: IfName=net1  Name=userspace-ovs-net-1  Type=vhost
|         |:   &{IPs:[10.56.217.166] Mac: DNS:{Nameservers:[] Domain: Search:[] Options:[]} Gateway:[]}
|         |:   Mode=client  Socketpath=/var/lib/cni/usrspcni/3d9fc3b7545d-net1
| 2       |: IfName=net2  Name=userspace-ovs-net-2  Type=vhost
|         |:   &{IPs:[10.77.217.154] Mac: DNS:{Nameservers:[] Domain: Search:[] Options:[]} Gateway:[]}
|         |:   Mode=client  Socketpath=/var/lib/cni/usrspcni/3d9fc3b7545d-net2
| 3       |: IfName=net3  Name=sriov-network  Type=sr-iov
|         |:   &{IPs:[10.56.217.90] Mac:da:18:1d:eb:ef:f2 DNS:{Nameservers:[] Domain: Search:[] Options:[]} Gateway:[]}
|         |:   PCI=0000:03:02.1
| 4       |: IfName=net4  Name=sriov-network  Type=sr-iov
|         |:   &{IPs:[10.56.217.91] Mac:fa:32:38:0e:b5:94 DNS:{Nameservers:[] Domain: Search:[] Options:[]} Gateway:[]}
|         |:   PCI=0000:03:04.3
```

**Pull request merged**
